# Generated by Django 5.1.5 on 2025-02-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_location', models.CharField(choices=[('Jaipur', 'Jaipur'), ('Khatu Shyam', 'Khatu Shyam'), ('Ajmer', 'Ajmer'), ('Salasar', 'Salasar'), ('Jaipur Junction', 'Jaipur Junction'), ('Jaipur Darshan', 'Jaipur Darshan'), ('Dausa', 'Dausa'), ('Behroad', 'Behroad'), ('Other', 'Other')], max_length=100)),
                ('destination', models.CharField(choices=[('Jaipur', 'Jaipur'), ('Khatu Shyam', 'Khatu Shyam'), ('Ajmer', 'Ajmer'), ('Salasar', 'Salasar'), ('Jaipur Junction', 'Jaipur Junction'), ('Jaipur Darshan', 'Jaipur Darshan'), ('Dausa', 'Dausa'), ('Behroad', 'Behroad'), ('Other', 'Other')], max_length=100)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('phone_no', models.CharField(max_length=10)),
                ('num_travelers', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
